# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb.proto',
  package='neardbv2.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08pb.proto\x12\x0bneardbv2.pb\")\n\nAddRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0f\n\x07taglist\x18\x02 \x03(\t\"\x1b\n\rRemoveRequest\x12\n\n\x02id\x18\x03 \x01(\x04\"\x0e\n\x0cNoneResponse\"9\n\x0cQueryRequest\x12\x0f\n\x07taglist\x18\x04 \x03(\t\x12\t\n\x01k\x18\x05 \x01(\x03\x12\r\n\x05\x64rift\x18\x06 \x01(\x01\"$\n\x04Item\x12\n\n\x02id\x18\x08 \x01(\x04\x12\x10\n\x08\x64istance\x18\t \x01(\x02\"1\n\rQueryResponse\x12 \n\x05items\x18\n \x03(\x0b\x32\x11.neardbv2.pb.Item2\xd1\x01\n\rNearDBService\x12;\n\x03\x41\x64\x64\x12\x17.neardbv2.pb.AddRequest\x1a\x19.neardbv2.pb.NoneResponse\"\x00\x12@\n\x05Query\x12\x19.neardbv2.pb.QueryRequest\x1a\x1a.neardbv2.pb.QueryResponse\"\x00\x12\x41\n\x06Remove\x12\x1a.neardbv2.pb.RemoveRequest\x1a\x19.neardbv2.pb.NoneResponse\"\x00\x62\x06proto3'
)




_ADDREQUEST = _descriptor.Descriptor(
  name='AddRequest',
  full_name='neardbv2.pb.AddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='neardbv2.pb.AddRequest.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taglist', full_name='neardbv2.pb.AddRequest.taglist', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=66,
)


_REMOVEREQUEST = _descriptor.Descriptor(
  name='RemoveRequest',
  full_name='neardbv2.pb.RemoveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='neardbv2.pb.RemoveRequest.id', index=0,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=95,
)


_NONERESPONSE = _descriptor.Descriptor(
  name='NoneResponse',
  full_name='neardbv2.pb.NoneResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=111,
)


_QUERYREQUEST = _descriptor.Descriptor(
  name='QueryRequest',
  full_name='neardbv2.pb.QueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='taglist', full_name='neardbv2.pb.QueryRequest.taglist', index=0,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='k', full_name='neardbv2.pb.QueryRequest.k', index=1,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='drift', full_name='neardbv2.pb.QueryRequest.drift', index=2,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=170,
)


_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='neardbv2.pb.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='neardbv2.pb.Item.id', index=0,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distance', full_name='neardbv2.pb.Item.distance', index=1,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=208,
)


_QUERYRESPONSE = _descriptor.Descriptor(
  name='QueryResponse',
  full_name='neardbv2.pb.QueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='neardbv2.pb.QueryResponse.items', index=0,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=259,
)

_QUERYRESPONSE.fields_by_name['items'].message_type = _ITEM
DESCRIPTOR.message_types_by_name['AddRequest'] = _ADDREQUEST
DESCRIPTOR.message_types_by_name['RemoveRequest'] = _REMOVEREQUEST
DESCRIPTOR.message_types_by_name['NoneResponse'] = _NONERESPONSE
DESCRIPTOR.message_types_by_name['QueryRequest'] = _QUERYREQUEST
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['QueryResponse'] = _QUERYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddRequest = _reflection.GeneratedProtocolMessageType('AddRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDREQUEST,
  '__module__' : 'pb_pb2'
  # @@protoc_insertion_point(class_scope:neardbv2.pb.AddRequest)
  })
_sym_db.RegisterMessage(AddRequest)

RemoveRequest = _reflection.GeneratedProtocolMessageType('RemoveRequest', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEREQUEST,
  '__module__' : 'pb_pb2'
  # @@protoc_insertion_point(class_scope:neardbv2.pb.RemoveRequest)
  })
_sym_db.RegisterMessage(RemoveRequest)

NoneResponse = _reflection.GeneratedProtocolMessageType('NoneResponse', (_message.Message,), {
  'DESCRIPTOR' : _NONERESPONSE,
  '__module__' : 'pb_pb2'
  # @@protoc_insertion_point(class_scope:neardbv2.pb.NoneResponse)
  })
_sym_db.RegisterMessage(NoneResponse)

QueryRequest = _reflection.GeneratedProtocolMessageType('QueryRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYREQUEST,
  '__module__' : 'pb_pb2'
  # @@protoc_insertion_point(class_scope:neardbv2.pb.QueryRequest)
  })
_sym_db.RegisterMessage(QueryRequest)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'pb_pb2'
  # @@protoc_insertion_point(class_scope:neardbv2.pb.Item)
  })
_sym_db.RegisterMessage(Item)

QueryResponse = _reflection.GeneratedProtocolMessageType('QueryResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYRESPONSE,
  '__module__' : 'pb_pb2'
  # @@protoc_insertion_point(class_scope:neardbv2.pb.QueryResponse)
  })
_sym_db.RegisterMessage(QueryResponse)



_NEARDBSERVICE = _descriptor.ServiceDescriptor(
  name='NearDBService',
  full_name='neardbv2.pb.NearDBService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=262,
  serialized_end=471,
  methods=[
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='neardbv2.pb.NearDBService.Add',
    index=0,
    containing_service=None,
    input_type=_ADDREQUEST,
    output_type=_NONERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='neardbv2.pb.NearDBService.Query',
    index=1,
    containing_service=None,
    input_type=_QUERYREQUEST,
    output_type=_QUERYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Remove',
    full_name='neardbv2.pb.NearDBService.Remove',
    index=2,
    containing_service=None,
    input_type=_REMOVEREQUEST,
    output_type=_NONERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NEARDBSERVICE)

DESCRIPTOR.services_by_name['NearDBService'] = _NEARDBSERVICE

# @@protoc_insertion_point(module_scope)
